# OneFilePicker appveyor.yml script

version: '{branch}-{build}'

branches:
  only:
    - master

os: Visual Studio 2022

before_build:
  nuget restore

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

configuration: Release

build:
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

deploy:
  provider: NuGet
  api_key:
    secure: fX84lcGQkh0YeCki2iAw6wbRemKLBjiB91HYKKK2vgd+mS9qxnJJ73cJp8FcuafF
  skip_symbols: false
